# yaml
name: Daily Build and Release

on:
  schedule:
    - cron: '0 18 * * *'  # 18h UTC = 1h sáng hôm sau theo giờ Việt Nam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Get current date in Asia/Ho_Chi_Minh
        id: date
        run: |
          echo "DATE=$(TZ='Asia/Ho_Chi_Minh' date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ env.DATE }}
          name: Nightly Build - ${{ env.DATE }}
          body: |
            ✅ This is an automated nightly build.
            📅 Built on: ${{ env.DATE }} (Asia/Ho_Chi_Minh time)
          files: |
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
